In [10]:
#Task 1
import numpy as np

In [11]:
#Task 2
temps = np.array([57, 55, 54, 53, 53, 54, 56, 60, 65, 70, 74, 78, 81, 83, 84, 84, 82, 79, 74, 70, 66, 63, 61, 59])
print(temps)
print(temps.shape)
print(temps.dtype)

[57 55 54 53 53 54 56 60 65 70 74 78 81 83 84 84 82 79 74 70 66 63 61 59]
(24,)
int64


In [12]:
#Task 3
temps_c = (temps - 32) * 5 / 9
print(temps_c)

[13.88888889 12.77777778 12.22222222 11.66666667 11.66666667 12.22222222
 13.33333333 15.55555556 18.33333333 21.11111111 23.33333333 25.55555556
 27.22222222 28.33333333 28.88888889 28.88888889 27.77777778 26.11111111
 23.33333333 21.11111111 18.88888889 17.22222222 16.11111111 15.        ]


In [13]:
#Task 4
print("Sum: ", np.sum(temps_c))
print("Mean: ", np.mean(temps_c))
print("Min: ", np.min(temps_c))
print("Max: ", np.max(temps_c))
print("Median: ", np.median(temps_c))

Sum:  470.55555555555554
Mean:  19.60648148148148
Min:  11.666666666666666
Max:  28.88888888888889
Median:  18.61111111111111


In [14]:
#Task 5
print(f"2:00 PM temperature: {temps[14]}°F")

2:00 PM temperature: 84°F


In [15]:
#Task 6
print(temps[12: 18])

[81 83 84 84 82 79]


In [18]:
#Task 7
# Hot Hours
hot_hours = temps[temps > 80]
print(hot_hours)
print("Number of hot hours: ", hot_hours.size)

[81 83 84 84 82]
Number of hot hours:  5


In [ ]:
#Task 8
sensor_grid = np.array([[81, 83, 84, 84, 82, 79],
                       [78, 80, 82, 83, 81, 77],
                       [83, 85, 87, 88, 86, 82]])
print(sensor_grid)
print(sensor_grid.shape)

[[81 83 84 84 82 79]
 [78 80 82 83 81 77]
 [83 85 87 88 86 82]]
(3, 6)


In [24]:
#Task 9
print("Sensor 3 hour 3 reading: ", sensor_grid[2, 3])
print("Sensor 2 readings", sensor_grid[1, :])
print("All senor readings for hour 1", sensor_grid[:, 0])


Sensor 3 hour 3 reading:  88
Sensor 2 readings [78 80 82 83 81 77]
All senor readings for hour 1 [81 78 83]
